---
language: python
python: "2.7"
dist: xenial
sudo: required
services:
  - docker
env:
  - SITE=test.yml

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce

install:
  # Install Ansible.
  - pip install ansible==2.5.4
  - pip install molecule
  - pip install docker

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
