---
- name: Set system hostname
  hostname:
    name: "{{ env_hostname }}"
  when: env_hostname|length

- name: Set system wide env variables
  lineinfile:
    dest: "/etc/environment"
    line: "{{ item.key }}='{{ item.value }}'"
    regexp: "^{{ item.key }} ?="
  with_dict: "{{ env_vars }}"
  no_log: true

- name: Set system wide locale env variable
  lineinfile:
    dest: "/etc/environment"
    line: "LC_ALL=en_US.UTF-8"

- name: Set system timezone
  copy:
    content: "{{ env_timezone }}\n"
    dest: "/etc/timezone"
  notify:
    - update timezone

- name: Set cron jobs
  cron:
    job: "{{ item.job }}"
    user: "{{ item.user }}"
    name: "{{ item.name }}"
    minute: "{{ item.minute|default('*') }}"
    hour: "{{ item.hour|default('*') }}"
    day: "{{ item.day|default('*') }}"
    month: "{{ item.month|default('*') }}"
    weekday: "{{ item.weekday|default('*') }}"
    state: "{{ item.state|default('present') }}"
  with_items: "{{ env_cron_jobs }}"
  when: env_cron_host is defined

- name: Add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ env_hostname }}"
  when: env_hostname|length

- name: Update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: " {{ item.host }}$"
    line: "{{ item.ip }} {{ item.host }}"
  with_items: "{{ env_hosts }}"

- name: Configure user pam environment variables
  pamd:
    name: sudo
    type: session
    control: required
    module_path: pam_env.so
    module_arguments: "readenv=1 user_readenv=1"
    state: updated
  when: env_pam_users | length

- name: Create home directory for pam users
  become: true
  user:
    name: "{{ item.name }}"
    create_home: true
  register: user_pam_registered
  loop: "{{ env_pam_users }}"
  when: env_pam_users | length

- name: Set proper directory permission
  become: true
  file:
    state: directory
    path: "{{ item.home }}"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ user_pam_registered.results }}"
  when: env_pam_users | length

- name: Copy pam_environment file to user home directory
  become: true
  become_user: "{{ item.name }}"
  template:
    src: "{{ item.template }}"
    dest: "~/.pam_environment"
    mode: 0640
  loop: "{{ env_pam_users }}"
  when: env_pam_users | length
