---
dependency:
  name: galaxy
driver:
  name: docker
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    image: ubuntu:16.04
    box: bento/ubuntu-16.04
    memory: 1024
    cpus: 1
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
